./24puzzleAbstraction1.out < ../Definitions/GoalState24Abstraction1.txt 24puzzleAbstraction1.pdb
./24puzzleAbstraction2.out < ../Definitions/GoalState24Abstraction2.txt 24puzzleAbstraction2.pdb
./24puzzleAbstraction3.out < ../Definitions/GoalState24Abstraction3.txt 24puzzleAbstraction3.pdb
./24puzzleAbstraction4.out < ../Definitions/GoalState24Abstraction4.txt 24puzzleAbstraction4.pdb
./24puzzleAbstraction5.out < ../Definitions/GoalState24Abstraction5.txt 24puzzleAbstraction5.pdb
#./24puzzleAbstraction6.out < ../Definitions/GoalState24Abstraction6.txt 24puzzleAbstraction6.pdb
./15puzzleAbstraction1.out < ../Definitions/GoalState15Abstraction1.txt 15puzzleAbstraction1.pdb
./15puzzleAbstraction2.out < ../Definitions/GoalState15Abstraction2.txt 15puzzleAbstraction2.pdb
./15puzzleAbstraction3.out < ../Definitions/GoalState15Abstraction3.txt 15puzzleAbstraction3.pdb
