make HanoiTower12DiskAbstraction1BottomDiskLess.out
make HanoiTower12DiskAbstraction11TopDiskLess.out

make HanoiTower14DiskAbstraction3BottomDiskless.out
make HanoiTower14DiskAbstraction11TopDiskless.out

make HanoiTower18DiskAbstraction7BottomDiskless.out
make HanoiTower18DiskAbstraction11TopDiskLess.out

make clean
