./HanoiTower12DiskAbstraction1BottomDiskLess.out < ../Definitions/GoalState12Abstraction1BottomDiskLess.txt HanoiTower12DiskAbstraction1BottomDiskLess.pdb
./HanoiTower12DiskAbstraction11TopDiskLess.out < ../Definitions/GoalState12Abstraction11TopDiskLess.txt HanoiTower12DiskAbstraction11TopDiskLess.pdb

./HanoiTower14DiskAbstraction3BottomDiskless.out < ../Definitions/GoalState14Abstraction3BottomDiskLess.txt HanoiTower14DiskAbstraction3BottomDiskless.pdb
./HanoiTower14DiskAbstraction11TopDiskless.out < ../Definitions/GoalState14Abstraction11TopDiskLess.txt HanoiTower14DiskAbstraction11TopDiskless.pdb

./HanoiTower18DiskAbstraction7BottomDiskless.out < ../Definitions/GoalState18Abstraction7BottomDiskLess.txt HanoiTower18DiskAbstraction7BottomDiskless.pdb
./HanoiTower18DiskAbstraction11TopDiskLess.out < ../Definitions/GoalState18Abstraction11TopDiskLess.txt HanoiTower18DiskAbstraction11TopDiskLess.pdb
